AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  HelloWorldLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs12.x
      Events:
        HelloWorldRoute:
          Type: Api
          Properties:
            Path: '/hello'
            Method: get
        HelloNameRoute:
          Type: Api
          Properties:
            Path: '/hello/{name}'
            Method: get

